export const PROFILE_ACTIVITIES_REQUEST = 'PROFILE_ACTIVITIES_REQUEST';
export const PROFILE_ACTIVITIES_SUCCESS = 'PROFILE_ACTIVITIES_SUCCESS';
export const PROFILE_ACTIVITIES_FAILED = 'PROFILE_ACTIVITIES_FAILED';
export const CERTIFICATES_REQUEST = 'CERTIFICATES_REQUEST';
export const CERTIFICATES_SUCCESS = 'CERTIFICATES_SUCCESS';
export const CERTIFICATES_FAILED = 'CERTIFICATES_FAILED';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
